### ISSUE TITLE
关于《一条经典面试题引发的思考》的一个问题

### ISSUE THREAD

**Issue by bwangelme** [samrayleung/blog#10]
您好，我阅读了您的文章[《一条经典面试题引发的思考》](http://samray.me/%E4%B8%80%E6%9D%A1%E7%BB%8F%E5%85%B8%E9%9D%A2%E8%AF%95%E9%A2%98%E5%BC%95%E5%8F%91%E7%9A%84%E6%80%9D%E8%80%83)之后对一些地方有异议，由于没在博客中找到评论的地方，所以冒昧将问题写在了这里，打扰之处，还请谅解。

## 问题描述

请问 第23行，在 continue 之前是否需要先执行 `Unlock` 操作。否则可能出现锁资源未释放的情况。

具体分析如下，我们将`i`的上限从30改成3，这样相当于希望每个线程只执行一次有效操作。

假设有这样的情况，线程 B 执行一次后，线程 C 正在上锁，此时`i`的值还没改变，线程 B判断`i < 3`继续循环。线程 C 执行成功后，线程 B加锁成功。此时`i`变成了3，线程 B 判断`i >= 3`，结束循环，线程 B 就有了一个加锁的锁资源未释放。

```java
     1  public void Test(){
     2      private static Integer index = 0;
     3      Lock lock = new ReentrantLock(true);
     4      @Test
     5      public void testLock(){
     6              Thread threadA = work(() -> System.out.println("A"));
     7              Thread threadB = work(() -> System.out.println("B"));
     8              Thread threadC = work(() -> System.out.println("C"));
     9              threadA.setName("threadA");
    10              threadA.start();
    11              threadB.setName("threadB");
    12              threadB.start();
    13              threadC.setName("threadC");
    14              threadC.start();
    15              System.out.println();
    16      }
    17
    18      private Thread work(Runnable function) {
    19              return new Thread(() -> {
    20                  while (index.intValue() < 3) {
    21                  lock.lock();
    22                  if (index >= 3) {
    23                      // lock.unlock();
    24                      continue;
    25                  }
    26                  if (condition.test(index.intValue())) {
    27                      function.run();
    28                      index++;
    29                  }
    30                  lock.unlock();
    31                  }
    32              });
    33      }
    34  }
```

**Comment by samrayleung** [comment]
>我阅读了您的文章《一条经典面试题引发的思考》之后对一些地方有异议

本来我写这篇博文，就是写了一个面试题错误答案之后的分析，主要是排查错误答案的历程，因为这个答案是错误的，所以有异议很正常的
>此时i变成了3，线程 B 判断i >= 3，结束循环，线程 B 就有了一个加锁的锁资源未释放。

虽然我没看懂您的描述(为我的理解能力抱歉)，我翻看代码，发现24行直接`continue`的确是有问题的:
```java
    22                  if (index >= 3) {
    23                      // lock.unlock();
    24                      continue;
    25                  }
```
虽然已经到循环的终结处(其实这里应该用`break`更好)，但是还是有资源出现`lock`之后没有`release`
的情况，只是因为循环已经结束，所以才没有暴露没有释放锁的问题.

仓促之下写下的另外一个"解决方案"没想到还是有问题的，真的是让人沮丧呢，anyway, 还是要感谢您的耐心阅读和细心斧正 :-)

**Comment by bwangelme** [comment]
> 虽然已经到循环的终结处(其实这里应该用break更好)，但是还是有资源出现lock之后没有release
的情况，只是因为循环已经结束，所以才没有暴露没有释放锁的问题.

啊，我想表达的就是这个意思。这个问题使用大段的文字描述，确实不太好理解。。。

**Comment by bwangelme** [comment]
@samrayleung 老哥吐槽一句。我把我的文章发到 V2 上以后，https://www.v2ex.com/t/552620  经过大家的讨论，才发现你的思路不太对啊。

这是一个同步问题，不是互斥问题，所以应该使用 `semaphore/channel` 去解决，而不是使用锁 + 自旋的思路解决，我跟着你的文章来写，思路也歪了。 🤣

**Comment by samrayleung** [comment]
情况的确如此，当初解这个面试题只是随手写了个能跑的答案，然后发到v2ex之后就被喷了，基本大家都在喷(无奈摊手脸.jpg)。其实我想表达的意思只是分析一下为什么我写的一个答案有问题: 我的推理思路是怎么样的，涉及到什么Jvm 并发知识，怎么去把问题解决。只是发到v2ex之后，都是在喷我解题方式不对，没有用condition啥的, 我也很无奈，这问题又没规定我用什么工具 (再次无奈摊手脸)。在此致歉，着实连累了用golang版本的老哥您了 :-)

**Comment by bwangelme** [comment]
老哥，“吐槽”只是开个玩笑啦。还是非常感谢你的分享，虽说你分享出来的东西不是完美的（我分享出来的也不是完美的），但是通过你的分享作为一个切入点，不断扩展开来，我还是学到了不少东西。希望你以后能多多分享。
